function file = addEscapes(file)
file = strrep(file,' ','\ ');
file = strrep(file,'-','\-');
file = strrep(file,'(','\(');
file = strrep(file,')','\)');
file = strrep(file,']','\]');
file = strrep(file,'[','\[');
file = strrep(file,'{','\{');
file = strrep(file,'}','\}');
file = strrep(file,'&','\&');
file = strrep(file,'''','\''');
file = strrep(file,'"','\"');
file = strrep(file,'.','\.');
file = strrep(file,'*','\*');
file = strrep(file,'?','\?');
file = strrep(file,';','\;');
file = strrep(file,'<','\<');
file = strrep(file,'>','\>');
file = strrep(file,'#','\#');
file = strrep(file,'!','\!');
end
